### ISSUE TITLE
Provide api to add more message sources

### ISSUE THREAD

**Issue by nerdbeere** [Vengarioth/Jarvis#3]
It would make sense to add more message sources than discord. To make this happen I think it would make sense to inject an array of `adapters` to jarvis that each provides a `on('message')` event.
`Jarvis` then listens for `message` events on all passed adapters.

What do you think?

**Comment by Vengarioth** [comment]
Yes, definitely, although we will move away from a per-message model to a per-conversation model, adapters also need to pre-process messages a bit and add identity information.
